-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.buku
(
    isbn character varying(10) COLLATE pg_catalog."default" NOT NULL,
    judul_buku character varying(100) COLLATE pg_catalog."default",
    sub_judul character varying(30) COLLATE pg_catalog."default",
    penerbit character varying(10) COLLATE pg_catalog."default",
    pengarang character varying(255) COLLATE pg_catalog."default",
    tahun_terbit character varying(10) COLLATE pg_catalog."default",
    halaman_buku character varying(10) COLLATE pg_catalog."default",
    kategori_id character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT buku_pkey PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public.category
(
    nomer_kategori character varying(10) COLLATE pg_catalog."default" NOT NULL,
    jenis character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT "Category_pkey" PRIMARY KEY (nomer_kategori)
);

CREATE TABLE IF NOT EXISTS public.login
(
    username character varying(10) COLLATE pg_catalog."default" NOT NULL,
    password character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public.peminjaman
(
    id_peminjaman character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nama character varying(11) COLLATE pg_catalog."default",
    isbn character varying(10) COLLATE pg_catalog."default",
    judul character varying(100) COLLATE pg_catalog."default",
    tanggal_peminjaman date,
    tanggal_kembali date,
    angkatan character varying(10) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT peminjaman_pkey PRIMARY KEY (id_peminjaman)
);

CREATE TABLE IF NOT EXISTS public.skripsi
(
    id_skripsi character varying(10) COLLATE pg_catalog."default" NOT NULL,
    judul_skripsi character varying(100) COLLATE pg_catalog."default",
    penulis_skripsi character varying(20) COLLATE pg_catalog."default",
    halaman_skripsi character varying(10) COLLATE pg_catalog."default",
    tahun_skripsi character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT skripsi_pkey PRIMARY KEY (id_skripsi)
);

ALTER TABLE IF EXISTS public.buku
    ADD CONSTRAINT buku_kategori_id_fkey FOREIGN KEY (kategori_id)
    REFERENCES public.category (nomer_kategori) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.peminjaman
    ADD CONSTRAINT fk_peminjaman_isbn FOREIGN KEY (isbn)
    REFERENCES public.buku (isbn) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;

END;